name: Bot de Publicación Automática con IA

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch: 

jobs:
  publicar_contenido:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar los archivos del repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías necesarias
        run: pip install google-generativeai requests

      - name: Enviar mensaje de prueba a Make
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"command": "run", "message": "Nueva publicación de prueba desde GitHub"}' \
          https://hook.us2.make.com/gkdah76ctpp6oiyw5y0yukmoklg26b8m

      - name: Ejecutar la Inteligencia Artificial y Enviar a Make
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python bot.py
